metrics:
  global:
    scrape_interval: 15s
  configs:
  - name: default
    scrape_configs:
      - job_name: 'tenant-service'
        static_configs:
          - targets: ['localhost:8080']
    remote_write:
      - url: http://prometheus:9090/api/v1/write

logs:
  configs:
  - name: default
    clients:
      - url: http://loki:3100/loki/api/v1/push
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
      - job_name: tenant-service
        static_configs:
          - targets: [localhost]
            labels:
              job: tenant-service
              __path__: /var/log/tenant-service/*.log