# application-dev.yml
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/tenant-service-db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa: 
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9080/realms/master
  cloud:
    config:
      enabled: false
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

app:
 client-ids:
   api: ae081f7c-f41f-431a-a797-c8ab62fe38c8
   ui: 44ab21a1-d07f-4d97-960b-2ef6ba935ded     
