spring:
    profiles:
      active:
        - dev
    application:
        name: tenant-service
    cloud:
        consul:
            host: localhost
            port: 8500 
    flyway:
      baseline-on-migrate: true        
    mail:
      host: smtp.gmail.com
      port: 587
      username: ${MAIL_USERNAME:}
      password: ${MAIL_PASSWORD:}
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
        debug: false
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  prometheus:
    metrics:
      export:
        enabled:  true           
         
keycloak:
  auth-server-url: http://localhost:9080
  master-realm: master
  admin-client-id: admin-cli
  admin-client-secret: a7B4K8bDolQ49K96r9kr1DZNSJzF1QI4
  admin-username: admin
  admin-password: admin123
  
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
 
  

# Application Configuration
app:
  auth:
    provider: KEYCLOAK  # Options: KEYCLOAK, AWS_COGNITO, AUTH0, SPRING_AUTH_SERVER
  tenant:
    default-settings:
      access-token-lifespan: 300
      refresh-token-lifespan: 1800
      sso-session-idle-timeout: 1800
      sso-session-max-lifespan: 36000
      allow-email-as-username: true
      email-verification-required: true
      registration-allowed: false
      remember-me: true
      minimum-password-length: 8
      require-uppercase: true
      require-lowercase: true
      require-numbers: true
      require-special-chars: false
      password-history-count: 3
      max-password-age: 90
      brute-force-detection: true
      max-failure-wait-seconds: 900
      wait-increment-seconds: 60
      max-delta-time-seconds: 43200
      failure-factor: 30
      min-quick-login-wait-seconds: 60
      max-quick-login-wait-seconds: 900
      otp-enabled: false
      otp-type: TOTP
      otp-digits: 6
      otp-period: 30
      otp-counter: 0
      otp-algorithm: 1
      google-login-enabled: false
      facebook-login-enabled: false
      microsoft-login-enabled: false
  client-ids:
   api: ae081f7c-f41f-431a-a797-c8ab62fe38c8
   ui: 44ab21a1-d07f-4d97-960b-2ef6ba935ded   
  base-url: ${APP_BASE_URL:http://localhost:8080}
  email:
    from: ${MAIL_FROM:noreply@offisync360.com}
    from-name: ${MAIL_FROM_NAME:OffiSync360}

# Rate Limiting Configuration
rate-limit:
  default:
    window-size-minutes: 15
    max-requests: 100
  signup:
    max-requests: 5
  login:
    max-requests: 10
  otp:
    max-requests: 3

# Mobile Verification Configuration
mobile-verification:
  otp-length: 6
  otp-expiry-minutes: 10
  max-attempts: 3
  max-requests-per-hour: 5

# Audit Configuration
audit:
  enabled: true
  retention-days: 90